package resetgen

import (
	"fmt"
	"path/filepath"

	"golang.org/x/tools/go/packages"
)

var (
	loadPackages = packages.Load
	absPath      = filepath.Abs
)

const generatedHeader = "// Code generated by reset generator. DO NOT EDIT.\n"

// Run scans all packages under the provided directory and generates reset methods
// for structs annotated with the "generate:reset" directive.
func Run(root string) error {
	absRoot, err := absPath(root)
	if err != nil {
		return fmt.Errorf("failed to resolve root directory: %w", err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
		Dir:  absRoot,
	}

	pkgs, err := loadPackages(cfg, "./...")
	if err != nil {
		return fmt.Errorf("failed to load packages: %w", err)
	}

	for _, pkg := range pkgs {
		if len(pkg.GoFiles) == 0 {
			continue
		}

		g := newGenerator(pkg)
		g.collectTargets()

		if len(g.targets) == 0 {
			continue
		}

		dir := filepath.Dir(pkg.GoFiles[0])
		g.filePath = filepath.Join(dir, "reset.gen.go")

		if err := g.generate(); err != nil {
			return fmt.Errorf("failed to generate for package %s: %w", pkg.Name, err)
		}
	}

	return nil
}
