POST /update/counter/someMetric/527 HTTP/1.1
Host: localhost:8080
Content-Length: 0
Content-Type: text/plain

###

POST /update/gauge/someMetric/42.5 HTTP/1.1
Host: localhost:8080
Content-Length: 0
Content-Type: text/plain
