// Code generated by reset generator. DO NOT EDIT.
package agent

func (obj *AppConfig) Reset() {
	if obj == nil {
		return
	}

	obj.Host = ""
	obj.Port = 0
	obj.ReportInterval = 0
	obj.PollInterval = 0
	obj.LoopIterations = 0
	obj.SignKey = ""
	obj.RateLimit = 0
}
